import * as pdfjs from './vendor/pdf.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.mjs';
const $=id=>document.getElementById(id); const names={lesson:'BOPPPS 教案生成',exam:'智能组卷',grade:'作业辅助批改',archive:'成果档案'};
let mode='lesson',busy=false,accessCode='',paperBytes=null,pdf=null,pages=[],notes={},pageIndex=0,renderToken=0;
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let drafts=safeRead('bkt-drafts',{}),archives=safeRead('bkt-archive',[]);
let endpoint=window.APP_CONFIG.apiUrl||safeRead('bkt-api','');
function persist(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true}catch{$('status').textContent='浏览器存储不可用，请下载成果备份。';return false}}
function connection(){$('connection').textContent=endpoint?'已设置生成接口':'未连接生成服务'} connection();
function syncResult(){const exists=!!$('result').value.trim();$('empty').hidden=exists;$('result').hidden=!exists;['download','print','save'].forEach(id=>$(id).disabled=!exists)}
function switchMode(next){if(busy)return;drafts[mode]=$('result').value;mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('heading').textContent=names[mode];$('subtitle').textContent={lesson:'从一个教学主题开始，组织一堂完整的课。',exam:'围绕教学目标编制试题，审核后形成考核材料。',grade:'依据评分量规给出建议，由教师确认每一份反馈。',archive:'保存教学成果，让下一次备课有据可循。'}[mode];$('workspace').hidden=mode==='archive';$('archive').hidden=mode!=='archive';$('annotation').hidden=mode!=='grade';$('exam-fields').hidden=mode!=='exam';$('grade-fields').hidden=mode!=='grade';$('generate').textContent={lesson:'生成教案',exam:'生成试卷与答案',grade:'生成批改建议'}[mode]||'生成';$('result').value=drafts[mode]||'';$('status').textContent='';syncResult();if(mode==='archive')renderArchive()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$('result').oninput=()=>{drafts[mode]=$('result').value;persist('bkt-drafts',drafts);syncResult()};
$('settings').onclick=()=>{$('api-url').value=endpoint;$('dialog').showModal()};$('close-settings').onclick=()=>$('dialog').close();$('save-settings').onclick=()=>{const value=$('api-url').value.trim();try{const u=new URL(value);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error();endpoint=value;accessCode=$('access-code').value;persist('bkt-api',value);connection();$('dialog').close()}catch{alert('请输入有效的 HTTPS 接口地址。')}};
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!endpoint){$('status').textContent='请先连接模型服务。当前不会使用模板替代 AI 生成。';$('settings').click();return}if(mode==='grade'&&(!$('answer').value.trim()||!$('rubric').value.trim())){$('status').textContent='请填写学生作答和评分量规。';return}busy=true;$('generate').disabled=true;$('status').textContent='正在生成，请稍候。你已有的成果会保留，直到新结果返回。';const payload={mode,topic:$('topic').value,audience:$('audience').value,minutes:Number($('minutes').value),requirements:$('requirements').value,material:$('material').value,count:Number($('count').value),total:Number($('total').value),types:$('types').value,answer:$('answer').value,rubric:$('rubric').value};try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(accessCode?{'X-Access-Code':accessCode}:{})},body:JSON.stringify(payload),signal:AbortSignal.timeout(120000)});let data;try{data=await response.json()}catch{throw Error('接口未返回有效结果，请检查服务地址。')}if(!response.ok)throw Error(data.error||'生成失败，请稍后重试。');if(typeof data.text!=='string'||!data.text.trim())throw Error('模型返回内容为空。');$('result').value=data.text;drafts[mode]=data.text;persist('bkt-drafts',drafts);syncResult();$('status').textContent='生成完成。请审核事实、题目答案与评分依据后使用。'}catch(err){$('status').textContent=err.name==='TimeoutError'?'生成超时，请稍后重试。':err.message==='Failed to fetch'?'无法连接生成服务，请检查接口地址、网络和跨域配置。':err.message}finally{busy=false;$('generate').disabled=false}};
function filename(){return ($('topic').value||names[mode]).replace(/[\/:*?"<>|]/g,'_').slice(0,70)}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('download').onclick=async()=>{try{const {Document,Paragraph,TextRun,Packer}=window.docx;const doc=new Document({styles:{default:{document:{run:{font:'Microsoft YaHei',size:22}}}},sections:[{properties:{},children:[new Paragraph({text:$('topic').value||names[mode],heading:'Heading1'}),...$('result').value.split('\n').map(line=>new Paragraph({children:[new TextRun(line)],spacing:{after:100}}))]}]});downloadBlob(await Packer.toBlob(doc),filename()+'.docx')}catch(e){$('status').textContent='导出失败：'+e.message}};
$('print').onclick=()=>{const w=window.open('','_blank');if(!w)return;w.document.title=filename();const pre=w.document.createElement('pre');pre.style.cssText='white-space:pre-wrap;font:16px/1.8 sans-serif';pre.textContent=$('result').value;w.document.body.append(pre);w.print()};
$('save').onclick=()=>{archives.unshift({id:crypto.randomUUID(),title:$('topic').value||names[mode],mode,text:$('result').value,time:new Date().toISOString()});archives=archives.slice(0,40);if(persist('bkt-archive',archives))$('status').textContent='已保存至本机成果档案。'};
function renderArchive(){const el=$('archive-list');el.replaceChildren();if(!archives.length){el.textContent='暂无保存的成果。生成并审核后，点击“保存到档案”。';return}for(const item of archives){const row=document.createElement('div');row.className='archive-item';const text=document.createElement('span');text.textContent=item.title+' · '+new Date(item.time).toLocaleDateString();const open=document.createElement('button');open.textContent='打开';open.onclick=()=>{switchMode(item.mode);$('topic').value=item.title;$('result').value=item.text;syncResult()};const del=document.createElement('button');del.textContent='删除';del.onclick=()=>{if(confirm('删除这份本机档案？')){archives=archives.filter(a=>a.id!==item.id);persist('bkt-archive',archives);renderArchive()}};row.append(text,open,del);el.append(row)}}
function wrap(ctx,text,maxWidth){const lines=[];for(const para of text.split('\n')){let line='';for(const c of para){if(ctx.measureText(line+c).width>maxWidth&&line){lines.push(line);line=c}else line+=c}lines.push(line)}return lines}
function noteLayer(width,height,page){const c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');for(const n of notes[page]||[]){ctx.font=`${Math.max(15,width*.018)}px "Microsoft YaHei",sans-serif`;const lines=wrap(ctx,n.text,width*.38),lh=Math.max(21,width*.025);const boxWidth=width*.4,boxHeight=lines.length*lh+12;const x=Math.min(n.x*width,width-boxWidth),y=Math.min(n.y*height,Math.max(0,height-boxHeight));ctx.fillStyle='rgba(255,255,255,.93)';ctx.fillRect(x,y,boxWidth,boxHeight);ctx.fillStyle='#be2929';lines.forEach((t,i)=>ctx.fillText(t,x+6,y+lh*(i+1)));}return c}
async function displayPage(){const token=++renderToken;const c=$('canvas');let source;if(pdf){const p=await pdf.getPage(pageIndex+1);const viewport=p.getViewport({scale:1.4});source=document.createElement('canvas');source.width=viewport.width;source.height=viewport.height;await p.render({canvasContext:source.getContext('2d'),viewport}).promise}else source=pages[pageIndex];if(token!==renderToken||!source)return;c.width=source.width;c.height=source.height;c.getContext('2d').drawImage(source,0,0);c.getContext('2d').drawImage(noteLayer(c.width,c.height,pageIndex),0,0)}
$('paper').onchange=async()=>{const f=$('paper').files[0];if(!f)return;notes={};pdf=null;paperBytes=null;pages=[];$('export-pdf').disabled=true;try{if(f.size>25*1024*1024)throw Error('请选择小于25MB的文件。');const bytes=new Uint8Array(await f.arrayBuffer());let count=1;if(f.type==='application/pdf'){paperBytes=bytes;pdf=await pdfjs.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;count=pdf.numPages;if(count>50)throw Error('请选择不超过50页的试卷。')}else{const bitmap=await createImageBitmap(f);const c=document.createElement('canvas');const ratio=Math.min(1,2200/Math.max(bitmap.width,bitmap.height));c.width=bitmap.width*ratio;c.height=bitmap.height*ratio;c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();pages=[c]}$('page-select').replaceChildren(...Array.from({length:count},(_,i)=>new Option('第 '+(i+1)+' 页',i)));pageIndex=0;await displayPage();$('export-pdf').disabled=false;$('paper-status').textContent='已加载原卷。输入评语后，点击页面放置。'}catch(e){pdf=null;paperBytes=null;pages=[];$('paper-status').textContent='加载失败：'+e.message}};
$('page-select').onchange=async()=>{pageIndex=Number($('page-select').value);await displayPage()};$('canvas').onclick=async e=>{const text=$('note').value.trim();if(!text){$('paper-status').textContent='请先填写评语文字。';return}const r=$('canvas').getBoundingClientRect();(notes[pageIndex]??=[]).push({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,text});await displayPage();$('paper-status').textContent='批注已添加，可切换页码继续批改。'};$('undo').onclick=async()=>{notes[pageIndex]?.pop();await displayPage()};
$('export-pdf').onclick=async()=>{const button=$('export-pdf');button.disabled=true;try{const {PDFDocument}=window.PDFLib;const out=await PDFDocument.create();const count=pdf?pdf.numPages:pages.length;for(let i=0;i<count;i++){let source;if(pdf){const page=await pdf.getPage(i+1),v=page.getViewport({scale:1.8});source=document.createElement('canvas');source.width=v.width;source.height=v.height;await page.render({canvasContext:source.getContext('2d'),viewport:v}).promise}else source=pages[i];const layer=noteLayer(source.width,source.height,i),combined=document.createElement('canvas');combined.width=source.width;combined.height=source.height;const ctx=combined.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,combined.width,combined.height);ctx.drawImage(source,0,0);ctx.drawImage(layer,0,0);const img=await out.embedPng(combined.toDataURL());out.addPage([595,595*combined.height/combined.width]).drawImage(img,{x:0,y:0,width:595,height:595*combined.height/combined.width});$('paper-status').textContent='正在导出第 '+(i+1)+' / '+count+' 页';}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'批改版试卷.pdf');$('paper-status').textContent='已导出完整批注试卷（页面图像版PDF）。请核对批注位置。'}catch(e){$('paper-status').textContent='导出失败：'+e.message}finally{button.disabled=false}};
switchMode('lesson');
